### ISSUE TITLE
Several typos and other such things

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern#2]
https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-1.xhtml#L120
"...has “the heart” against it even a doctrine..." should be "...has “the heart” against it: even a doctrine...
(missing colon)
https://archive.org/details/beyondgoodandevi00nietuoft/page/26/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-2.xhtml#L96
"...makes an abuse of this name a very narrow..." should be "...makes an abuse of this name: a very narrow..."
(missing colon)
and: "...for everyone, their two..." should be "...for everyone; their two..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/48/mode/2up
"...in which he concealed..." should be "...in which lie concealed..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/50/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-3.xhtml#L20
"...is sacrifice the sacrifice..." should be "...is sacrifice: the sacrifice..."
(missing colon)
"...of spirit, it is at..." should be "...of spirit; it is at..."
"...fastidious conscience, it takes..." should be "...fastidious conscience; it takes..."
"...of non-faith, and it..." should be "...of non-faith; and it..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/52/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-3.xhtml#L24
"...will-renunciation, both symptoms..." should be "...will-renunciation: both symptoms..."
"...put aside explanations around no..." should be "...put aside explanations: around no..."
(missing colons)
https://archive.org/details/beyondgoodandevi00nietuoft/page/54/mode/2up
"...at this point, is it not possible..." should be "...at this point; is it not possible..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/56/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L20
"...and gave superiority..." should be "...and gain superiority..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/96/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L24
the first and third uses of "laisser-aller" should probably be italicized?

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L35
"πϱόσϑε Πλάτων τε Πλάτων μέσση Χίμαιϱα." should be "πϱόσϑε Πλάτων ὄπισθέν τε Πλάτων μέσση τε Χίμαιϱα."
https://archive.org/details/beyondgoodandevi00nietuoft/page/100/mode/2up

In general there's a problem with a lot of semi-colons from the original being replaced with commas. I likely didn't catch most of them, just a few of the more awkward ones. Given Nietzsche's convoluted sentence structures, those semi-colons are pretty important in keeping distinct phrases distinct. I probably didn't catch all the missing colons either.

**Comment by acabal** [comment]
Fixed!
