### ISSUE TITLE
Another big batch of typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern#3]
https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L73
"...gregarious men all representative..." should be "...gregarious men: all representative..."
"...the last great proof the history..." should be "...the last great proof: the history..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/110/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L81
"...is destroyed, its belief..." should be "...is destroyed; its belief..."
"...breaks, consequently..." should be "...breaks; consequently..."
"...dangers, everything..." should be "...dangers; everything..."
"...evil, the tolerant..." should be "...evil; the tolerant..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/112/mode/2up
"...the herd “we wish..." should be "...the herd: “we wish..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/114/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-5.xhtml#L85
"...European influence prevails in Europe..." should be "...European influence prevails: in Europe..."
"...morality in europe..." should be "...morality in Europe..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/114/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L16
"...scholar those philosophers..." should be "...scholar: those philosophers..."
"...philosophy After..." should be "...philosophy. After..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/120/mode/2up
"...pity Philosophy..." should be "...pity. Philosophy..."
"...of forbearance a philosophy..." should be "...of forbearance: a philosophy..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/122/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L20
"...a milleantenna, he knows..." should be "...a milleantenna; he knows..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/122/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L28
"...knowledge” The..." should be "...knowledge.” The..."
"...himself” The..." should be "...himself.” The..."
"...film Whatever..." should be "...film. Whatever..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/124/mode/2up
"...himself He does..." should be "...himself. He does..."
"...to himself he is serene..." should be "...to himself: he is serene..."
"...trouble The..." should be "...trouble. The..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/126/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L32
"...culture It..." should be "...culture. It..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/128/mode/2up
"...skepticism The..." should be "...skepticism. The..."
"...physicists) Perhaps..." should be "...physicists). Perhaps..."
"...breakfast I do..." should be "...breakfast. I do..."
"...desires it, in my..." should be "...desires it; in my..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/130/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L36
"...saw Goethe it reveals..." should be "...saw Goethe: it reveals..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/132/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L40
"...love of attempting is this..." should be "...love of attempting: is this..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/132/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L44
"...remain standing he..." should be "...remain standing: he..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/134/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-6.xhtml#L48
"...outlived, they have..." should be "...outlived; they have..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/136/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/86fe09c95858ebe4f5b49b33dbaecf854059f745/src/epub/text/part-7.xhtml#L36
"...them furious, I shall..." should be "...them furious; I shall..."
"...of generations, that lofty..." should be "...of generations; that lofty..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/144/mode/2up

**Comment by acabal** [comment]
Thanks! As usual, if you're in the process of reading this, please group all of your fixes into a single issue or PR. That makes it much easier for me to manage. If you're not done reading, then please wait until you're finished so you can submit them all at once. Thank you!
