### ISSUE TITLE
last batch from me

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern#4]
https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L20
"in politicis" should be italicized
https://archive.org/details/beyondgoodandevi00nietuoft/page/172/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L60
"antiSemitic" should be "antisemitic" or "anti-Semitic" or something else.
"antiSemitism" should be "antisemitism" or "anti-Semitism" or something else.
"...as the Jews are such..." should be "...as the Jews are: such..."
"...nobility do It..." should be "...nobility do. It..."
"...Prussian border it would..." should be "...Prussian border: it would..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/186/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L64
"...je meprise Locke..." should be "...je méprise Locke..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/186/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L69
"noblesse" -- italicize?

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L82
"antiChristian" should probably be "anti-Christian"

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-8.xhtml#L83
The section beginning "—Is this our mode?" needs to be formatted as verse rather than just glommed into a paragraph
https://archive.org/details/beyondgoodandevi00nietuoft/page/196/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-9.xhtml#L24
"...each other it will..." should be "...each other: it will..."
"...primitive society it belongs..." should be "...primitive society: it belongs..."
"...Life—Granting... should be "...Life. — Granting..."
"...all history let us..." should be "...all history: let us..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/200/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-9.xhtml#L28
"...displays itself he despises..." should be "...displays itself: he despises..."
https://archive.org/details/beyondgoodandevi00nietuoft/page/200/mode/2up
"gai saber" should probably be italicized
https://archive.org/details/beyondgoodandevi00nietuoft/page/204/mode/2up

https://github.com/standardebooks/friedrich-nietzsche_beyond-good-and-evil_helen-zimmern/blob/250bf7d4fbbb62bb74061d8b76905872b81a7943/src/epub/text/part-9.xhtml#L64
"...animal! success..." should be "...animal! Success..." (capitalize S)
https://archive.org/details/beyondgoodandevi00nietuoft/page/216/mode/2up

**Comment by acabal** [comment]
All fixed, thanks!
